pipeline {
    agent any
    tools {
        maven 'M2_HOME'
    }
    stages {
        stage('sonar-scan'){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=yosuaosae_geo-1'
            }
           
        }
        stage('maven') {
            steps {
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact') {
            steps {
                sh '''
                curl -u admin:AP9EAEqsfnmeHcMRi1pXe34qyAU -T \
                target/bio*.jar \
                "http://ec2-54-86-211-250.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"
                '''
            }
        }
    }
}
