pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
     stage("SonarQube analysis") {          
            steps {
             withSonarQubeEnv('sonarq') {
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=geolocation_geosolution'

             }
            }
        }
    stage("maven"){
        steps{ 
        sh 'mvn clean '
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://ec2-52-91-134-51.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
    }
    stage('docker login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            076892551558.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    stage('docker image build'){
        steps{
            sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
        }
    }
    stage('Image tagging'){
        steps{
            sh 'docker tag utc-app-dev:v.${BUILD_ID} \
            076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'

        }
    }
    stage('push image'){
        steps{  
        sh 'docker push 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
        sh 'docker push 076892551558.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
    }
    }
  
   } 
  
}

